name: Build and publish a php8-apache image
on:
  workflow_dispatch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  VER : 7.4

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags:  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:7.4
          build-args: |
            PHP_VERSION=7.4
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags:  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:8.0
          build-args: |
            PHP_VERSION=8.0
      - name: Get Image Details
        run: |
          docker image ls
